spring:
  name: transfer-api
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: mappings,functions

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"