server:
  port: 8082

spring:
  name: transfer-processor
  redis:
    host: localhost
    port: 6379
  cloud:
    function:
      definition: process
    stream:
      bindings:
        process-in-0:
          destination: process-in
          content-type: text/plain
        process-out-0:
          destination: process-out
          content-type: text/plain

management:
  endpoints:
    web:
      exposure:
        include: mappings,functions

logging:
  level:
    org.springframework.cloud.stream: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
